name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/workflows/on_push_main.yaml

env:
  AWS_REGION: us-east-1
  NODE_ENV: production
  TF_VERSION: latest
  TG_VERSION: 0.31.8

jobs:
  default:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    environment:
      name: production
      url: https://mr.codermarcos.zone/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TG_VERSION }}
          tg_command: apply --terragrunt-non-interactive --terragrunt-working-dir iac --terragrunt-source .
